### ISSUE TITLE
Missing functions throwing an error for search results, should we just remove these or add the functions?

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/quotesondev-starter#3]
https://github.com/redacademy/quotesondev-starter/blob/7b6f04b5d3965d68779f14dbbbeed77a80a9dc23/template-parts/content-search.php#L16

**Comment by mobyg** [comment]
unsubscribe please.

**Comment by resonantdoghouse** [comment]
> unsubscribe please.

Hi @garryhicks this is actually something you can do :) please click the Unwatch icon to stop following this repo.
